apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
      - name: payments
        image: sosghazaryan/payments
        env:
          - name: STRIPE_KEY
            value: "sk_test_51NLLHUCb5IoHRQkPZdhHtuiarI2TG88v1UvSRHaGQzsmzovuFayyxn5PFWvpWGiidgOcT7T8CAyiw8RD4fiUmQMA00RNWZjVY1"
          - name: JWT_KEY
            valueFrom:
              secretKeyRef:
                name: jwt-secret
                key: JWT_KEY
          - name: MONGO_URI
            value: payments-mongo-srv
          - name: MONGO_DB_NAME
            value: payments
          - name: NATS_URL
            value: http://nats-srv:4222
          - name: NATS_CLUSTER_ID
            value: ticketing
          - name: NATS_CLIENT_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          
---
apiVersion: v1
kind: Service
metadata:
  name: payments-srv
spec:
  selector:
    app: payments
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
