name: order-tests
on:
  pull_request:
    paths:
      - 'orders/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd orders && npm instal && npm run test:ci
